export const OrderStatus = {
  DRAFT: "DRAFT",
  LABEL_CREATED: "LABEL_CREATED",
  PENDING_LABEL: "PENDING_LABEL",
  LABEL_NOT_CREATED: "LABEL_NOT_CREATED",
  WAITING_FOR_PICKUP: "WAITING_FOR_PICKUP",
  PICKED_UP: "PICKED_UP",
  PACKAGE_RECEIVED: "PACKAGE_RECEIVED",
  RECEIVED_AT_ORIGIN_WAREHOUSE: "RECEIVED_AT_ORIGIN_WAREHOUSE",
  ON_THE_WAY: "ON_THE_WAY",
  EXPORT_CUSTOMS_CLEARANCE: "EXPORT_CUSTOMS_CLEARANCE",
  DEPARTED_ORIGIN_COUNTRY: "DEPARTED_ORIGIN_COUNTRY",
  INTERNATIONAL_TRANSIT: "INTERNATIONAL_TRANSIT",
  ARRIVED_AT_DESTINATION_COUNTRY: "ARRIVED_AT_DESTINATION_COUNTRY",
  IMPORT_CUSTOMS_CLEARANCE: "IMPORT_CUSTOMS_CLEARANCE",
  RECEIVED_BY_LAST_MILE_CARRIER: "RECEIVED_BY_LAST_MILE_CARRIER",
  PICK_UP: "PICK_UP",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERY: "DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  EXCEPTION: "EXCEPTION",
} as const;

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export const ShippingMethod = {
  EPACKET: "EPACKET",
  EXPRESS: "EXPRESS",
} as const;

export type ShippingMethod = (typeof ShippingMethod)[keyof typeof ShippingMethod];

export const GroupOrderStatus = {
  LABEL_NOT_CREATED: "LABEL_NOT_CREATED",
  LABEL_CREATED: "LABEL_CREATED",
  WE_HAVE_YOUR_PACKAGE: "WE_HAVE_YOUR_PACKAGE",
  ON_THE_WAY: "ON_THE_WAY",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  EXCEPTION: "EXCEPTION",
} as const;

export type GroupOrderStatus = (typeof GroupOrderStatus)[keyof typeof GroupOrderStatus];
